pickle_dir: 'midi_dataset_dir'
epochs: 1000
batch_size: 2
load_path:
dropout: 0.1
debug: 'true'
l_r: 0.001
label_smooth: 0.1
experiment: 'embedding256-layer6'
max_seq: 2048
embedding_dim: 128
num_layers: 3
event_dim: 388